title: YAPI
description: YAPI
baseurl: '/yapi' # the subpath of your site, e.g. /blog

theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

include: [documents, devops]

defaults:
  - scope:
      path: '' # 一个空的字符串代表项目中所有的文件
    values:
      layout: 'default'

plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
